"""Celery task: "Generate all 7 posts" batch.

Reads the BatchGenerateProgress row, walks the 7 cached content-plan days, and
for each day generates an image (Gemini → DALL-E fallback) + a caption (via the
extracted `generate_caption_text` helper from ai_pages), then creates a
scheduled_post row. Per-day failures are logged into `per_day_status` and the
batch keeps walking — one bad day does not block the rest of the week.

Action modes:
  - "drafts"   → all 7 posts saved with status='draft', scheduled_at=NULL
  - "schedule" → each post saved with status='scheduled', scheduled_at built
                 from (date + best_time). If the resulting time is already in
                 the past or within SCHEDULE_TOO_CLOSE_MIN minutes from now,
                 that day falls back to a draft (recorded as
                 fell_back_to_draft=true so the UI can flag it).

per_day_status JSONB shape (keyed by day_index as string):
  {
    "0": {
      "status": "queued|generating_image|generating_caption|saving|done|failed",
      "scheduled_post_id": "<uuid>" | null,
      "error": "<string>" | null,
      "fell_back_to_draft": false
    },
    ...
  }
"""
from __future__ import annotations

import logging
from datetime import date as _date, datetime, time as _time, timedelta, timezone
from sqlalchemy.orm.attributes import flag_modified

from app.api.v1.ai_pages import generate_caption_text
from app.core.ai_image import (
    analyze_image_url,
    generate_dalle_image,
)
from app.core.ai_provider import AIProviderError
from app.core.celery_app import celery
from app.core.database import SessionLocal
from app.models.ai_page_cache import AiPageCache
from app.models.batch_generate_progress import BatchGenerateProgress
from app.models.organization import Organization
from app.models.scheduled_post import ScheduledPost

logger = logging.getLogger(__name__)


# Minutes-from-now threshold below which "schedule" mode falls back to a draft.
# Five minutes covers Instagram's dispatcher cadence (every minute) plus media
# upload latency — anything closer than that risks scheduling a post that the
# dispatcher won't pick up until after the user-facing "best time" has passed.
SCHEDULE_TOO_CLOSE_MIN = 5

# 15-day cleanup TTL matches the per-day wizard (DRAFT_TTL in posts_creator.py).
# Drafts created by the batch are real drafts and should follow the same
# cleanup policy.
DRAFT_TTL_DAYS = 15

# Default content-type → media-type mapping for the scheduled_post row. The
# wizard creates images today; carousel + video aren't generated by the batch
# (the batch always emits a single image). We still respect the day's
# content_type for the AI-suggested caption tone, but the media_type field is
# always "image" because that's what we produced.
DEFAULT_MEDIA_TYPE = "image"

# Image ratio used for batch generation. 1:1 is the safest default — works for
# images, doesn't crop, and matches the wizard's default. A future iteration
# could pick per-day based on content_type (e.g. 4:5 for portrait), but the
# spec doesn't ask for that and the consistency reads better in the UI.
DEFAULT_RATIO = "1:1"


def _day_status_template() -> dict:
    return {
        f"{i}": {
            "status": "queued",
            "scheduled_post_id": None,
            "error": None,
            "fell_back_to_draft": False,
        }
        for i in range(7)
    }


def _scheduled_at_for_day(date_str: str, best_time: str) -> datetime | None:
    """Compose a UTC datetime from (YYYY-MM-DD, HH:MM). Returns None on parse
    failure — the caller falls back to a draft when None is returned."""
    try:
        d = _date.fromisoformat(date_str)
        hh, mm = (best_time or "18:00").split(":")
        return datetime.combine(d, _time(int(hh), int(mm)), tzinfo=timezone.utc)
    except (ValueError, IndexError):
        return None


def _update_progress(db, progress: BatchGenerateProgress, day_idx: int, **fields) -> None:
    """In-place mutation of per_day_status[day_idx], then commit. JSONB columns
    don't auto-detect deep mutations — flag_modified ensures SQLAlchemy ships
    the new value on commit."""
    if not isinstance(progress.per_day_status, dict):
        return
    entry = progress.per_day_status.setdefault(
        str(day_idx), {"status": "queued", "scheduled_post_id": None, "error": None, "fell_back_to_draft": False},
    )
    entry.update(fields)
    flag_modified(progress, "per_day_status")
    db.commit()


@celery.task(name="batch_generate_content_plan", bind=True)
def batch_generate_content_plan(self, batch_id: str) -> dict:
    """Walks the cached Content Plan days and generates posts for each.

    The Celery task ID and the BatchGenerateProgress row are decoupled — the
    endpoint creates the row first (returning its id to the frontend) and then
    enqueues this task with the row's id as the argument. That way the
    frontend always has a valid progress key even if .delay() fails (the
    endpoint can mark the row as failed without losing the user's batch_id).
    """
    db = SessionLocal()
    try:
        progress = (
            db.query(BatchGenerateProgress)
            .filter(BatchGenerateProgress.id == batch_id)
            .first()
        )
        if not progress:
            logger.warning("batch_generate: row not found id=%s", batch_id)
            return {"status": "not_found", "batch_id": batch_id}

        social_account_id = str(progress.social_account_id)
        organization_id = str(progress.organization_id)
        language = progress.language
        action = progress.action

        # Pull the cached plan — the only source of truth for the 7 topics +
        # dates + content types. If the plan was busted by a "Regenerate" click
        # between dialog and task pickup, we surface that as an explicit error
        # on the batch instead of silently producing 7 empty-topic posts.
        cache_row = (
            db.query(AiPageCache)
            .filter(
                AiPageCache.social_account_id == social_account_id,
                AiPageCache.page_name == "content-plan",
                AiPageCache.language == language,
            )
            .first()
        )
        if not cache_row or not cache_row.content:
            progress.status = "failed"
            progress.error_message = "Content plan no longer available — please regenerate the plan and try again."
            progress.completed_at = datetime.now(timezone.utc)
            db.commit()
            return {"status": "failed", "reason": "missing_cache"}

        topics_by_idx = (cache_row.content or {}).get("topics_by_idx") or {}

        # Rebuild the 7-day skeleton the same way the GET endpoint does — same
        # rotation, same best-hours. We could include this in the cache payload
        # but the spec wanted the cache to keep just topics; reconstructing the
        # skeleton here keeps the cache schema unchanged.
        days_meta = _rebuild_days_skeleton(db, social_account_id, topics_by_idx)
        if len(days_meta) != 7:
            progress.status = "failed"
            progress.error_message = "Could not rebuild 7-day plan."
            progress.completed_at = datetime.now(timezone.utc)
            db.commit()
            return {"status": "failed", "reason": "bad_skeleton"}

        account_ids = [progress.social_account_id]

        for day in days_meta:
            day_idx = day["day_index"]
            topic = day.get("topic") or ""
            content_type = day.get("content_type") or "image"
            date_str = day["date"]
            best_time = day.get("best_time") or "18:00"

            if not topic.strip():
                _update_progress(
                    db, progress, day_idx,
                    status="failed",
                    error="No topic suggested for this day. Regenerate the plan and try again.",
                )
                continue

            # ── Step 1: image ─────────────────────────────────────────
            _update_progress(db, progress, day_idx, status="generating_image", error=None)

            brand = {}
            bp = {}
            org = (
                db.query(Organization)
                .filter(Organization.id == organization_id)
                .first()
            )
            if org:
                brand = org.brand_identity or {}
                bp = org.business_profile or {}

            from app.api.v1.posts_creator import _build_dalle_prompt
            try:
                prompt = _build_dalle_prompt(topic, DEFAULT_RATIO, brand, bp)
                image_result = generate_dalle_image(
                    prompt,
                    ratio=DEFAULT_RATIO,
                    account_id=social_account_id,
                    source="user",
                )
            except AIProviderError as exc:
                logger.warning(
                    "batch_generate: image failed batch=%s day=%s err=%s",
                    batch_id, day_idx, exc,
                )
                _update_progress(
                    db, progress, day_idx,
                    status="failed",
                    error=exc.user_message,
                )
                continue
            except Exception as exc:  # noqa: BLE001
                logger.exception("batch_generate: unexpected image error batch=%s day=%s", batch_id, day_idx)
                _update_progress(
                    db, progress, day_idx,
                    status="failed",
                    error=f"Image generation failed: {exc}",
                )
                continue

            image_url = image_result.get("url") or ""

            # ── Step 1b: image analysis (best-effort — captions still work
            # without it) ─────────────────────────────────────────────
            image_analysis: dict | None = None
            try:
                image_analysis = analyze_image_url(
                    image_url, account_id=social_account_id, source="user",
                )
            except AIProviderError:
                # Vision is optional — caption can still go without it.
                image_analysis = None
            except Exception:  # noqa: BLE001
                image_analysis = None

            # ── Step 2: caption ──────────────────────────────────────
            _update_progress(db, progress, day_idx, status="generating_caption")
            try:
                caption_text = generate_caption_text(
                    db,
                    account_ids=account_ids,
                    primary_account_id=social_account_id,
                    content_type=content_type,
                    topic=topic,
                    language=language,
                    reference_caption=None,
                    post_id=None,
                    image_ratio=DEFAULT_RATIO,
                    image_analysis=image_analysis,
                    source="user",
                )
            except AIProviderError as exc:
                logger.warning(
                    "batch_generate: caption failed batch=%s day=%s err=%s",
                    batch_id, day_idx, exc,
                )
                _update_progress(
                    db, progress, day_idx,
                    status="failed",
                    error=exc.user_message,
                )
                continue
            except Exception as exc:  # noqa: BLE001
                logger.exception("batch_generate: unexpected caption error batch=%s day=%s", batch_id, day_idx)
                _update_progress(
                    db, progress, day_idx,
                    status="failed",
                    error=f"Caption generation failed: {exc}",
                )
                continue

            # ── Step 3: persist ScheduledPost ─────────────────────────
            _update_progress(db, progress, day_idx, status="saving")
            now = datetime.now(timezone.utc)

            scheduled_at: datetime | None = None
            fell_back_to_draft = False
            post_status = "draft"
            draft_expires_at = now + timedelta(days=DRAFT_TTL_DAYS)

            if action == "schedule":
                composed = _scheduled_at_for_day(date_str, best_time)
                threshold = now + timedelta(minutes=SCHEDULE_TOO_CLOSE_MIN)
                if composed is None or composed < threshold:
                    fell_back_to_draft = True
                    post_status = "draft"
                else:
                    scheduled_at = composed
                    post_status = "scheduled"
                    draft_expires_at = None

            caption_ar = caption_text if language == "ar" else None
            caption_en = caption_text if language == "en" else None

            post = ScheduledPost(
                organization_id=organization_id,
                social_account_id=social_account_id,
                media_urls=[image_url] if image_url else [],
                media_type=DEFAULT_MEDIA_TYPE,
                caption_ar=caption_ar,
                caption_en=caption_en,
                hashtags=[],
                ratio=DEFAULT_RATIO,
                scheduled_at=scheduled_at,
                status=post_status,
                ai_generated_media=bool(image_url),
                ai_generated_caption=bool(caption_text),
                source_image_url=image_url or None,
                image_analysis=image_analysis,
                content_plan_day=_date.fromisoformat(date_str),
                draft_expires_at=draft_expires_at,
            )
            db.add(post)
            db.commit()
            db.refresh(post)

            _update_progress(
                db, progress, day_idx,
                status="done",
                scheduled_post_id=str(post.id),
                fell_back_to_draft=fell_back_to_draft,
                error=None,
            )

        # All 7 days walked. Compute final status: "completed" unless every
        # day failed, in which case "failed" so the UI doesn't look like a
        # success when there's nothing to show.
        final_statuses = [
            (progress.per_day_status.get(str(i)) or {}).get("status", "failed")
            for i in range(7)
        ]
        all_failed = all(s == "failed" for s in final_statuses)
        progress.status = "failed" if all_failed else "completed"
        progress.completed_at = datetime.now(timezone.utc)
        if all_failed and not progress.error_message:
            progress.error_message = "All 7 days failed. Try regenerating the content plan."
        db.commit()

        return {
            "status": progress.status,
            "batch_id": batch_id,
            "per_day_status": progress.per_day_status,
        }

    except Exception as exc:  # noqa: BLE001
        logger.exception("batch_generate: unexpected outer failure id=%s", batch_id)
        try:
            db.rollback()
            row = (
                db.query(BatchGenerateProgress)
                .filter(BatchGenerateProgress.id == batch_id)
                .first()
            )
            if row and row.status == "running":
                row.status = "failed"
                row.error_message = f"Unexpected error: {exc}"
                row.completed_at = datetime.now(timezone.utc)
                db.commit()
        except Exception:  # noqa: BLE001
            logger.exception("batch_generate: cleanup also failed id=%s", batch_id)
        raise
    finally:
        db.close()


def _rebuild_days_skeleton(db, social_account_id: str, topics_by_idx: dict) -> list[dict]:
    """Reconstruct the 7-day skeleton the same way GET /content-plan does.

    Returns one dict per day with `day_index`, `date`, `content_type`,
    `best_time`, and the cached `topic`. Same rotation logic as the endpoint
    so a batch invoked right after a GET produces posts for the exact same
    day topics the user saw on screen.
    """
    from sqlalchemy import func
    from app.models.engagement_metric import EngagementMetric
    from app.models.post import Post

    type_stats = (
        db.query(
            Post.content_type,
            func.count(Post.id).label("n"),
            func.coalesce(func.avg(EngagementMetric.likes + EngagementMetric.comments), 0).label(
                "avg_eng"
            ),
        )
        .outerjoin(EngagementMetric, EngagementMetric.post_id == Post.id)
        .filter(Post.social_account_id == social_account_id)
        .group_by(Post.content_type)
        .order_by(func.coalesce(func.avg(EngagementMetric.likes + EngagementMetric.comments), 0).desc())
        .all()
    )
    type_rotation: list[str] = []
    for row in type_stats:
        if not row.content_type:
            continue
        type_rotation.append(row.content_type.value)
    if not type_rotation:
        type_rotation = ["image", "video", "carousel"]

    best_hour_by_type: dict[str, int] = {}
    hour_rows = (
        db.query(
            Post.content_type,
            func.extract("hour", Post.posted_at).label("hour"),
            func.avg(EngagementMetric.likes + EngagementMetric.comments).label("avg_eng"),
        )
        .join(EngagementMetric, EngagementMetric.post_id == Post.id)
        .filter(Post.social_account_id == social_account_id)
        .group_by(Post.content_type, "hour")
        .all()
    )
    by_type_hour: dict[str, list[tuple[int, float]]] = {}
    for row in hour_rows:
        if not row.content_type or row.hour is None:
            continue
        by_type_hour.setdefault(row.content_type.value, []).append(
            (int(row.hour), float(row.avg_eng or 0))
        )
    for ct, pairs in by_type_hour.items():
        pairs.sort(key=lambda p: p[1], reverse=True)
        best_hour_by_type[ct] = pairs[0][0] if pairs else 18

    today = datetime.now(timezone.utc).date()
    day_names = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
    days = []
    for i in range(7):
        d = today + timedelta(days=i)
        ct = type_rotation[i % len(type_rotation)]
        hour = best_hour_by_type.get(ct, 18)
        days.append(
            {
                "day_index": i,
                "day_label": day_names[d.weekday()],
                "date": d.isoformat(),
                "content_type": ct,
                "best_time": f"{hour:02d}:00",
                "topic": (topics_by_idx or {}).get(str(i), ""),
            }
        )
    return days


__all__ = [
    "batch_generate_content_plan",
    "SCHEDULE_TOO_CLOSE_MIN",
    "_day_status_template",
]
